version: '2'
services:
    itaste-app:
        image: itaste
        external_links:
            - itaste-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=iTaste
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    itaste-mongodb:
        extends:
            file: mongodb.yml
            service: itaste-mongodb
