version: '2'
services:
    itaste-mongodb:
        container_name: itaste-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/iTaste/mongodb/:/data/db/
